# Generated by Django 5.1.5 on 2025-05-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
