# Generated by Django 5.1.5 on 2025-05-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='high',
            field=models.DecimalField(decimal_places=2, help_text='Use 9999 for unlimited', max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='productlineitem',
            name='price_each',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
