# Generated by Django 3.2.4 on 2022-09-11 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListCategory',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'list categories',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('mailman', 'Mailman')], max_length=10)),
                ('order', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex=re.compile('^[a-z][a-z0-9-]*$'))])),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailinglist.listcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mail_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailinglist.mailinglist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='listmember',
            constraint=models.UniqueConstraint(fields=('mail_list', 'email'), name='member'),
        ),
    ]
