# Generated by Django 2.2 on 2019-06-09 03:25

from django.db import migrations, models
import django.db.models.deletion

def create_PaymentMethod(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    values = [
        dict(slug='cash',   name='Cash',        in_gate=True),
        dict(slug='check',  name='Check',       in_gate=True),
        dict(slug='credit', name='Credit Card', in_gate=False),
    ]

    model = apps.get_model('gate', 'PaymentMethod')
    model.objects.using(db_alias).bulk_create([
        model(**kwargs) for kwargs in values
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_PaymentMethod),
    ]
