# Generated by Django 3.2.4 on 2021-06-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0004_prices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'permissions': (('signin_app', 'Can use signin app'), ('books_app', 'Can use books app'))},
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
