# Generated by Django 3.2.4 on 2022-09-12 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0007_add_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
