# Generated by Django 3.2.25 on 2025-02-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_alter_personauthlink_create_reason_basic'),
        ('gate', '0009_add_price_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership.person',),
        ),
    ]
