# Generated by Django 5.1.5 on 2025-05-18 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0011_autofield'),
        ('membership', '0010_autofield'),
        ('money', '0002_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionLineItem',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='money.lineitem')),
                ('subscriber_name', models.CharField(max_length=50)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.person')),
                ('sub_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gate.subscriptionperiod')),
            ],
            bases=('money.lineitem',),
        ),
    ]
