# Generated by Django 5.1.5 on 2025-05-06 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0011_autofield'),
        ('membership', '0010_autofield'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('stage', models.IntegerField(choices=[(10, 'cart'), (20, 'paid')])),
            ],
        ),
        migrations.CreateModel(
            name='CybersourceLineItem',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gate.lineitem')),
                ('receipt_post', models.JSONField()),
            ],
            bases=('gate.lineitem',),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gate.transaction'),
        ),
        migrations.CreateModel(
            name='SubscriptionLineItem',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gate.lineitem')),
                ('person_name', models.CharField(max_length=50)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.person')),
                ('sub_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gate.subscriptionperiod')),
            ],
            bases=('gate.lineitem',),
        ),
    ]
