# Generated by Django 5.1.5 on 2025-05-06 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0011_autofield'),
        ('membership', '0010_autofield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('stage', models.IntegerField(choices=[(10, 'cart'), (20, 'paid')])),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('person_name', models.CharField(max_length=50)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.person')),
                ('sub_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gate.subscriptionperiod')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gate.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CybersourceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('receipt_post', models.JSONField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gate.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
