# Generated by Django 5.1.5 on 2025-05-06 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0012_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stage',
            field=models.IntegerField(choices=[(10, 'cart'), (40, 'review'), (50, 'paid'), (60, 'cancel')]),
        ),
    ]
