# Generated by Django 5.1.5 on 2025-05-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0013_payments_more_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybersourcelineitem',
            name='decision',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cybersourcelineitem',
            name='ref_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stage',
            field=models.IntegerField(choices=[(10, 'Cart'), (40, 'Review'), (50, 'Paid'), (60, 'Cancel')]),
        ),
    ]
