# Generated by Django 5.1.5 on 2025-05-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0014_payments_more_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='account_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
