# Generated by Django 5.1.5 on 2025-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0015_payments_more_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybersourcelineitem',
            name='card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cybersourcelineitem',
            name='card_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cybersourcelineitem',
            name='ref_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
