# Generated by Django 5.1.5 on 2025-05-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0016_payments_more_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionlineitem',
            old_name='person_name',
            new_name='subscriber_name',
        ),
    ]
