# Generated by Django 5.1.5 on 2025-05-10 04:22

import squaresdb.gate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0017_pay_rename_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nonce',
            field=models.CharField(default=squaresdb.gate.models.Transaction.default_nonce, max_length=16),
        ),
    ]
