# Generated by Django 5.1.5 on 2025-05-13 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0018_pay_nonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('account_name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='displayed to users')),
                ('admin_notes', models.TextField(blank=True, help_text='internal item notes')),
                ('low', models.DecimalField(decimal_places=2, max_digits=5)),
                ('high', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='account_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ProductLineItem',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gate.lineitem')),
                ('count', models.IntegerField()),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gate.product')),
            ],
            bases=('gate.lineitem',),
        ),
    ]
