# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_personauthlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('view_person', 'Can view people'),), 'verbose_name_plural': 'people'},
        ),
    ]
