# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 06:55
from __future__ import unicode_literals

from typing import List

from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_personauthlink'),
    ]

    operations = [
    ] # type: List[Operation]
