# Generated by Django 2.2 on 2019-05-02 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_add_view_person_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='membership.SquareLevel', verbose_name='highest level'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mit_affil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.MITAffil', verbose_name='MIT affiliation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.PersonStatus', verbose_name='membership status'),
        ),
        migrations.AlterField(
            model_name='personauthlink',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auth_links_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personauthlink',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auth_links', to='membership.Person'),
        ),
        migrations.AlterField(
            model_name='tsclassassist',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.TSClass', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='tsclassmember',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.TSClass', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='tsclassmember',
            name='pe',
            field=models.BooleanField(verbose_name='taking class as PE student?'),
        ),
    ]
