# Generated by Django 2.2 on 2019-05-02 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_add_on_delete'),
    ]

    operations = [
        # Allow blank/null creators -- this is used when resending invalid
        # PersonAuthLink objects, since that doesn't require authenticating
        migrations.AlterField(
            model_name='personauthlink',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auth_links_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
