# Generated by Django 2.2 on 2019-06-09 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_allow_unknown_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='grad_year',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='year (expected or actual) graduated from MIT'),
        ),
        migrations.AlterField(
            model_name='personcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments_written', to=settings.AUTH_USER_MODEL),
        ),
    ]
