# Generated by Django 3.2.4 on 2022-02-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_personfreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personauthlink',
            name='create_reason_basic',
            field=models.CharField(max_length=50),
        ),
    ]
