all:
    children:
        prod:
            hosts:
                squares-google:
                    ansible_user: root
                    extname: squaresdb.mit.edu
                    # Note that changing these requires some manual actions
                    # (blowing away some LE state is probably sufficient)
                    vhost_aliases:
                        - squaresdb-google.dehnerts.com
                    dbtype: mysql
                    enable_logging: false
                    cybersource: prod

        test:
            hosts:
                squares-dehnert:
                    ansible_user: root
                    extname: squaresdb.dehnerts.com
                    vhost_aliases: []
                    dbtype: sqlite
                    enable_logging: true
                    #cybersource: test
                    cybersource: mock
